[client]
showErrorDetails = true
showWarningOnDirectExecution = false

[logger]
level = "info"

[server]
headless = true
port = 8501
enableXsrfProtection = true
maxUploadSize = 200

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
font = "sans serif"
